name: Deploy
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install -g serverless
      - name: Deploy to AWS
        env:
          PIXLET_API_TOKEN: ${{ secrets.PIXLET_API_TOKEN }}
          PIXLET_DEVICE_ID: virulently-courageous-pleasing-boxer-d48
          INSTALLATION_ID: nycbustime
          BUS_TIMES_API_KEY: ${{ secrets.BUS_TIMES_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: serverless deploy
